### ISSUE TITLE
Add css file

### ISSUE THREAD

**Issue by cupcakearmy** [impostersussy/CircularStd#1]
Was to lazy to fork, maybe add the following CSS file :)

```css
/* Normal 450 */
@font-face {
  font-family: 'Circular Std';
  font-weight: 450;
  font-style: normal;
  font-display: swap;
  src: url('./CircularStd-Book.eot');
  src: url('./CircularStd-Book.eot?#iefix') format('embedded-opentype'),
      url('./CircularStd-Book.woff2') format('woff2'),
      url('./CircularStd-Book.ttf') format('truetype'),
      url('./CircularStd-Book.svg#CircularStd-Book') format('svg');
}
@font-face {
  font-family: 'Circular Std';
  font-weight: 450;
  font-style: italic;
  font-display: swap;
  src: url('./CircularStd-BookItalic.eot');
  src: url('./CircularStd-BookItalic.eot?#iefix') format('embedded-opentype'),
      url('./CircularStd-BookItalic.woff2') format('woff2'),
      url('./CircularStd-BookItalic.ttf') format('truetype'),
      url('./CircularStd-BookItalic.svg#CircularStd-BookItalic') format('svg');
}

/* Medium 500 */
@font-face {
  font-family: 'Circular Std';
  font-weight: 500;
  font-style: normal;
  font-display: swap;
  src: url('./CircularStd-Medium.eot');
  src: url('./CircularStd-Medium.eot?#iefix') format('embedded-opentype'),
      url('./CircularStd-Medium.woff2') format('woff2'),
      url('./CircularStd-Medium.ttf') format('truetype'),
      url('./CircularStd-Medium.svg#CircularStd-Medium') format('svg');
}
@font-face {
  font-family: 'Circular Std';
  font-weight: 500;
  font-style: italic;
  font-display: swap;
  src: url('./CircularStd-MediumItalic.eot');
  src: url('./CircularStd-MediumItalic.eot?#iefix') format('embedded-opentype'),
      url('./CircularStd-MediumItalic.woff2') format('woff2'),
      url('./CircularStd-MediumItalic.ttf') format('truetype'),
      url('./CircularStd-MediumItalic.svg#CircularStd-MediumItalic') format('svg');
}

/* Bold 700 */
@font-face {
  font-family: 'Circular Std';
  font-weight: 700;
  font-style: normal;
  font-display: swap;
  src: url('./CircularStd-Bold.eot');
  src: url('./CircularStd-Bold.eot?#iefix') format('embedded-opentype'),
      url('./CircularStd-Bold.woff2') format('woff2'),
      url('./CircularStd-Bold.ttf') format('truetype'),
      url('./CircularStd-Bold.svg#CircularStd-Bold') format('svg');
}
@font-face {
  font-family: 'Circular Std';
  font-weight: 700;
  font-style: italic;
  font-display: swap;
  src: url('./CircularStd-BoldItalic.eot');
  src: url('./CircularStd-BoldItalic.eot?#iefix') format('embedded-opentype'),
      url('./CircularStd-BoldItalic.woff2') format('woff2'),
      url('./CircularStd-BoldItalic.ttf') format('truetype'),
      url('./CircularStd-BoldItalic.svg#CircularStd-BoldItalic') format('svg');
}

/* Black 900 */

@font-face {
  font-family: 'Circular Std';
  font-weight: 900;
  font-style: normal;
  font-display: swap;
  src: url('./CircularStd-Black.eot');
  src: url('./CircularStd-Black.eot?#iefix') format('embedded-opentype'),
      url('./CircularStd-Black.woff2') format('woff2'),
      url('./CircularStd-Black.ttf') format('truetype'),
      url('./CircularStd-Black.svg#CircularStd-Black') format('svg');
}
@font-face {
  font-family: 'Circular Std';
  font-weight: 900;
  font-style: italic;
  font-display: swap;
  src: url('./CircularStd-BlackItalic.eot');
  src: url('./CircularStd-BlackItalic.eot?#iefix') format('embedded-opentype'),
      url('./CircularStd-BlackItalic.woff2') format('woff2'),
      url('./CircularStd-BlackItalic.ttf') format('truetype'),
      url('./CircularStd-BlackItalic.svg#CircularStd-BlackItalic') format('svg');
}

```
